### ISSUE TITLE
Error while setting up platform alexa_media

### ISSUE THREAD

**Issue by Zifro96** [keatontaylor/alexa_media_player#239] opened 2019-06-30 14:27 UTC
![Mediaplayer_alexa](https://user-images.githubusercontent.com/32470926/60398014-e9495980-9b53-11e9-81df-7f0641b50102.jpg)

**Comment by Spirituss** [comment] 2019-06-30 16:55
The same issue. This is the log:
```ERROR (MainThread) [homeassistant.components.alarm_control_panel] Error while setting up platform alexa_media
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity_platform.py", line 126, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 400, in wait_for
    return fut.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/alexa_media/alarm_control_panel.py", line 34, in setup_platform
    hass)  \
  File "/home/homeassistant/.homeassistant/custom_components/alexa_media/alarm_control_panel.py", line 71, in __init__
    ['locationDetails']['Default_Location']
KeyError: 'Default_Location'
```

**Comment by alandtse** [comment] 2019-06-30 17:26
Please ensure you're on 1.3.1.

**Comment by ElPotton** [comment] 2019-07-02 08:49
The same issue And I also confirm that the version is correct.
ps: echo dot is not available
Tnx and good work

**Comment by Spirituss** [comment] 2019-07-02 11:10
> Please ensure you're on 1.3.1.

I updated manually to 1.3.1, the problem is gone. But I was not able to update 1.3.0 by custom updater component. Just nothing was changing if I press 'Update all' button.

**Comment by alandtse** [comment] 2019-07-03 02:42
@ElPotton I don't understand. Did you resolve it or are you seeing the issue still with 1.3.1? If you see the issue, I'll need debugging logs to review.

@Spirituss `Custom_updater` is deprecated. Use [HACS](https://github.com/keatontaylor/alexa_media_player/wiki#hacs---home-assistant-community-store-versions--130) instead.

**Comment by Spirituss** [comment] 2019-07-03 15:08
@alandtse Thanks for the support! I changed custom_updater to HACS, works well.

**Comment by ElPotton** [comment] 2019-07-04 12:19
@alandtse

Tnx for the help, i hope this is what you ment.

2019-07-02 09:43:24 ERROR (MainThread) [homeassistant.helpers.entity] Update for media_player.danieledi_fire_tv_stick fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 220, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 377, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/alexa_media/media_player.py", line 428, in update
    no_throttle=True)
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 224, in wrapper
    result = method(*args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 224, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/alexa_media/media_player.py", line 256, in refresh
    self._last_called = self._get_last_called()
  File "/config/custom_components/alexa_media/media_player.py", line 357, in _get_last_called
    ['serialNumber']))
TypeError: 'NoneType' object is not subscriptable
2019-07-02 09:43:24 ERROR (MainThread) [homeassistant.helpers.entity] Update for media_player.this_device fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 220, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 377, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/alexa_media/media_player.py", line 428, in update
    no_throttle=True)
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 224, in wrapper
    result = method(*args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 224, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/alexa_media/media_player.py", line 256, in refresh
    self._last_called = self._get_last_called()
  File "/config/custom_components/alexa_media/media_player.py", line 357, in _get_last_called

**Comment by alandtse** [comment] 2019-07-05 06:08
Thanks. @ElPotton Can you please try deleting your cookie file and relogging in? The error you're getting happens if we're not logging in correctly. If other devices are working, is that echo shared between other accounts?

**Comment by ElPotton** [comment] 2019-07-05 07:47
@alandtse
Tnx for the help.
I tried your solution but the situation didn’t change. 
My echo isn’t shared with the other accounts.
In standby state there are only ‘firetv’ and ‘this_device’ whereas ‘echo_dot’ and ‘alexa_app’ are unavailable.
What am i doing wrong

**Comment by alandtse** [comment] 2019-07-05 07:51
What region are you in and what domain have you set up in your configuration.yaml? The error you're describing happens if you're logging into Amazon from the wrong region from where your devices are setup.  For example, if your devices are setup in Germany and you login through amazon.com.

**Comment by ElPotton** [comment] 2019-07-05 07:57
My region is Italy, i’m logged in with amazon.com
Do I have to try with amazon.co.it?

**Comment by alandtse** [comment] 2019-07-05 07:59
@ElPotton Yes, use `amazon.it`

**Comment by ElPotton** [comment] 2019-07-05 08:40
@alandtse
fantastic, it works now
tnx a lot

**Comment by alandtse** [comment] 2019-07-13 06:04
Closing since other haven't reported more details. Please feel free to reopen if you have an issue for us to debug.

**Closed by alandtse** 2019-07-13 06:04 UTC

**Comment by DedicatedF100** [comment] 2019-08-02 16:52
I seem to be having a slight issue with my Alexa_media Also. Seems to be other than location error too. 
![image](https://user-images.githubusercontent.com/52455856/62385898-49049d00-b524-11e9-9c6c-598cbcbaeecd.png)
