### ISSUE TITLE
JSON Generated by Routine doesn't match JSON Generated by alexa_media_player for announcements

### ISSUE THREAD

**Issue by brettyj** [keatontaylor/alexa_media_player#185] opened 2019-05-10 13:15 UTC
As asked to do so here: https://community.home-assistant.io/t/echo-devices-alexa-as-media-player-testers-needed/58639/2662?u=brettyj here are the differences - as my announce/push to mobile/tts/play media functionality doesn't seem to work.

Alexa app routines:
```
"sequence":{  
   "@type":"com.amazon.alexa.behaviors.model.Sequence",
   "sequenceId":"amzn1.alexa.sequence.c8abf752-d43a-4b50-841d-77b7c34c0dd0",
   "startNode":{  
      "@type":"com.amazon.alexa.behaviors.model.OpaquePayloadOperationNode",
      "type":"AlexaAnnouncement",
      "skillId":"amzn1.ask.1p.messaging",
      "operationPayload":{  
         "expireAfter":"PT5S",
         "content":[  
            {  
               "locale":"en-GB",
               "display":{  
                  "title":"Alexa Routines",
                  "body":"Test"
               },
               "speak":{  
                  "type":"text",
                  "value":"Test"
               }
            }
         ],
         "customerId":"CUSTOMERID",
         "target":{  
            "customerId":"CUSTOMERID"
         }
      },
      "name":null
   }
},
```
alexa_media_player:
```
{  
   “behaviorId”:“PREVIEW”,
   “sequenceJson”:“   {  
      ”@type":“com.amazon.alexa.behaviors.model.Sequence”,
      “startNode”:{  
         "@type":“com.amazon.alexa.behaviors.model.OpaquePayloadOperationNode”,
         “type”:“AlexaAnnouncement”,
         “operationPayload”:{  
            “deviceType”:“DEVICETYPEID”,
            “deviceSerialNumber”:“SERIALNUMBER”,
            “locale”:“en-gb”,
            “customerId”:“CUSTOMERID”,
            “expireAfter”:“PT5S”,
            “content”:[  
               {  
                  “locale”:“en-gb”,
                  “display”:{  
                     “title”:“Home Assistant”,
                     “body”:“test”
                  },
                  “speak”:{  
                     “type”:“text”,
                     “value”:“test”
                  }
               }
            ],
            “target”:{  
               “customerId”:“CUSTOMERID”,
               “devices”:[  
                  {  
                     “deviceSerialNumber”:“SERIALNUMBER”,
                     “deviceTypeId”:“DEVICETYPEID”
                  }
               ]
            }
         }
      }
   }   ",
   “status”:“ENABLED”
}
```

There are a few differences, the ones that stand out to me are
`"skillId":"amzn1.ask.1p.messaging"` and that the routine JSON doesn't care about target devices (I selected announce to all) I suspect it's the skillid that's causing the issue though, although I haven't done any alexa dev so could be wrong.

Thanks

**Comment by alandtse** [comment] 2019-05-11 06:07
Thanks. Can you also do a test for the same target just so we're comparing the same things?

**Comment by brettyj** [comment] 2019-05-13 11:58
```
"sequence":{  
   "@type":"com.amazon.alexa.behaviors.model.Sequence",
   "sequenceId":"amzn1.alexa.sequence.52dd65b8-3830-4635-903b-9b91f25f9f46",
   "startNode":{  
      "@type":"com.amazon.alexa.behaviors.model.OpaquePayloadOperationNode",
      "type":"AlexaAnnouncement",
      "skillId":"amzn1.ask.1p.messaging",
      "operationPayload":{  
         "expireAfter":"PT5S",
         "content":[  
            {  
               "locale":"en-GB",
               "display":{  
                  "title":"Alexa Routines",
                  "body":"Test"
               },
               "speak":{  
                  "type":"text",
                  "value":"Test"
               }
            }
         ],
         "customerId":"CUSTOMERID",
         "target":{  
            "customerId":"CUSTOMERID",
            "devices":[  
               {  
                  "deviceSerialNumber":"DEVICESERIAL",
                  "deviceTypeId":"DEVICETYPE"
               }
            ]
         }
      },
      "name":null
   }
},
```

Again the main difference seems to be the `"skillId":"amzn1.ask.1p.messaging"`

**Comment by alandtse** [comment] 2019-05-16 07:24
Just to verify, you've only ever used 1.2.5 right? You didn't upgrade from 1.2.4?  We also made a change related to locale in 1.2.5 and I want to make sure that wasn't the cause.

**Comment by alandtse** [comment] 2019-05-17 06:28
Can you try the [1.2.4 release](https://github.com/keatontaylor/alexa_media_player/releases/tag/v1.2.4)? I want to make sure it's the `skillId` and not related to the locale changes we made.

**Comment by brettyj** [comment] 2019-05-17 19:17
Hey,

I tried the 1.2.4 release and it still didn't work - so I don't think it's the locale changes

**Comment by alandtse** [comment] 2019-05-18 08:51
Thanks. Can you use the Alexa app to also test `Alexa says` and `Messaging - Notifications` to see if it also has `"skillId":"amzn1.ask.1p.messaging"` or some other value? Might as well try to get them all consistent.

Also want to check some basic things too:

1. What is the `url` set to for configuration.yaml? I'd think it has to be a uk domain given the en-gb locale reporting.
2. Are your devices only on a single email account or shared? If shared, what happens if you use the other account? If you check the [devices page (fix url domain as appropriate)](https://alexa.amazon.com/api/devices-v2/device), you can see that they have a `deviceOwnerCustomerId` which may be different from the logged in user. I know you're redacting the `customerId` above, but please see if it matches the `deviceOwnerCustomerId`.

**Comment by brettyj** [comment] 2019-05-18 19:16
Hey,

Looks like the skills are:
"skillId": "amzn1.ask.1p.messaging"
"skillId": "amzn1.ask.1p.saysomething"
"skillId": "amzn1.ask.1p.alexanotifications"

````"nodesToExecute": [
{
"@type": "com.amazon.alexa.behaviors.model.OpaquePayloadOperationNode",
"type": "AlexaAnnouncement",
"skillId": "amzn1.ask.1p.messaging",
"operationPayload": {
"expireAfter": "PT5S",
"content": [
{
"locale": "en-GB",
"display": {
"title": "Alexa Routines",
"body": "Test"
},
"speak": {
"type": "text",
"value": "Test"
}
}
],
"customerId": "CUSTOMERID",
"target": {
"customerId": "CUSTOMERID",
"devices": [
{
"deviceSerialNumber": "DEVICESERIAL",
"deviceTypeId": "DEVICETYPE"
}
]
}
},
"name": null
},
{
"@type": "com.amazon.alexa.behaviors.model.OpaquePayloadOperationNode",
"type": "Alexa.Speak",
"skillId": "amzn1.ask.1p.saysomething",
"operationPayload": {
"customerId": "CUSTOMERID",
"deviceType": "ALEXA_CURRENT_DEVICE_TYPE",
"deviceSerialNumber": "ALEXA_CURRENT_DSN",
"textToSpeak": "Test",
"locale": "en-GB"
},
"name": null
},
{
"@type": "com.amazon.alexa.behaviors.model.OpaquePayloadOperationNode",
"type": "Alexa.Notifications.SendMobilePush",
"skillId": "amzn1.ask.1p.alexanotifications",
"operationPayload": {
"customerId": "CUSTOMERID",
"notificationMessage": "Test",
"alexaUrl": "#v2/behaviors",
"title": "Amazon Alexa"
},
"name": null
}
]
````

My configuration url is amazon.co.uk
The device deviceOwnerCustomerId generated by alexa-media-player matches that of the devices page.

My devices are shared with my partner, used her details and it works weirdly even though the devices are registered to me. Here's the winning call:

````
{"behaviorId": "PREVIEW", "sequenceJson": "{\"@type\": \"com.amazon.alexa.behaviors.model.Sequence\", \"startNode\": {\"@type\": \"com.amazon.alexa.behaviors.model.OpaquePayloadOperationNode\", \"type\": \"AlexaAnnouncement\", \"operationPayload\": {\"deviceType\": \"DEVICETYPE\", \"deviceSerialNumber\": \"DEVICESERIALNUMBER\", \"locale\": \"en-US\", \"customerId\": \"PARTNERSCUSTOMERID\", \"expireAfter\": \"PT5S\", \"content\": [{\"locale\": \"en-US\", \"display\": {\"title\": \"Home Assistant\", \"body\": \"test\"}, \"speak\": {\"type\": \"text\", \"value\": \"test\"}}], \"target\": {\"customerId\": \"PARTNERSCUSTOMERID\", \"devices\": [{\"deviceSerialNumber\": \"G090LF1072070GWJ\", \"deviceTypeId\": \"DEVICETYPE\"}]}}}}", "status": "ENABLED"}
````
Very odd as the deviceOwnerCustomerId on devices is definitely mine not hers. *shrugs*
`

**Comment by alandtse** [comment] 2019-05-18 23:48
Glad to see it worked with the account swap.  One last question, when you were making the working call using the app, did it have your customerId or your partner's customerId?

Thanks again for helping with all the detail. I'll see about adding the `skillId` but I think the issue is probably the customerId.  I will test whether adding the `skillId` does any damage and will close this out after I've done that.  It'd help if you edited your first post to add a note the fix was to switch to another shared account and if you could also edit the FAQ so we catch this use case.

**Comment by alandtse** [comment] 2019-05-20 08:13
Ok, I took a look at this and adding the skillId would be a significant change since it's based on a run_sequence function that is shared by every sequence skill. This would mean potentially adding the skillId for every Amazon sequence. I'll defer this for now since I don't think it's needed.

**Closed by alandtse** 2019-05-20 08:13 UTC
Labels: alexapy
