### ISSUE TITLE
issue loading component

### ISSUE THREAD

**Issue by sparkyx64** [keatontaylor/alexa_media_player#142] opened 2019-03-27 02:39 UTC
Fresh install on a Debian 9 server, HA is set as a python3 venv based on the manual install under another username instructions...

Folder for custom components/alexa_media/ is set correctly with all four python files just added today

For some reason, everytime I try to load with the config file populated with the correct setup info, it hangs, soon as I comment it out, pulls fine. Log file pulls the following
>2019-03-26 22:11:44 ERROR (MainThread) [homeassistant.bootstrap] Error loading /home/homeassistant/.homeassistant/configuration.yaml: Secret alexa_password not defined

This is my config for the alexa_media at the bottom of my configuration.yaml, proper indents, and user/pass is plain text to eliminate a possible secret.yaml issue

 

>alexa_media:
>  accounts:
>    - email: "REDACTED@REDACTED.com"
>      password: "REDACTED"
 >     url: amazon.com

Ive tried with the secrets file, without it.. Ive even installed a fresh Debian/HA install with no components on a test box to try to see if this is a localized problem, and im getting the same issue, not sure whats going on, but would love some insight.

HA Version is 0.90.1

**Comment by alandtse** [comment] 2019-03-27 06:22
It looks like a [formatting error](https://github.com/keatontaylor/alexa_media_player/wiki/Configuration#configure-ha).  If you want us to be able to help, please don't use blockquotes but [appropriate quoting](https://community.home-assistant.io/t/echo-devices-alexa-as-media-player-testers-needed/58639/2488) so it doesn't destroy the yaml indents/chars.

**Comment by sparkyx64** [comment] 2019-04-04 01:09
alandtse, you’ve been commenting on my posts in the HA threads, I’ve tried everything from using double or single quotes, to no quotes, using secret file to not using secrets and putting plaintext for user name and password. The only thing I’ve found that doesn’t immediately hang the server is renaming the init.py file from “__init__.py” to “init.py”. I’m honestly at a loss of why it’s not working. The only odd thing is the hass check (check config button) just spins and spins.

Any insight on this would be appreciated.

**Comment by alandtse** [comment] 2019-04-04 03:41
Please do not double post across the forums and the github. If you want help here, you'll need to update the issue with your config and the logs for the specific configuration attempt. These summaries where you don't provide any detail do not help us figure out what's wrong.

Please provide:

- HA version.
- alexa_media version:  From `__init__.py`
- Configuration properly quoted.
- Results of `hass --script check_config` for every iteration you want us to review.  If you want to do something with quotes, include that as a separate version. I've already told you to remove them.

**Comment by sparkyx64** [comment] 2019-04-05 01:17
Double posted because I didnt seem to get help or it ran in circles. Ive ran this on two machines, one Ubuntu 18.04LTS with HA 0.91 and one Debian Stretch with HA 0.90, both with latest updates, and both are doing the same thing.

not sure on the version, cant find the line of code that has a version in init.py, i just pulled the most recent one tonight, 1.2.3, and thats what im having issues with.

HA Config

```
> alexa_media:
>   accounts:
>     - email: email@email.com
>       password: password
>       url: amazon.com
```

I just tried it on a fresh instance on Ubuntu, HA version 0.91, and its the only thing ive added and changed from a stock/fresh install. If I add the config as above, and files as required by instructions, HA hangs. 

Check Config bears the result of `Component not found: alexa_media` when i first initially add custom component files and the config change to include the "alexa_media" config, and then once I change the __init__.py name to exclude the underscores. That or completely removing the files/config is the only thing that allows HA to go from hung on a component to working

Im open to suggestions, let me know if im missing any info or if more is needed

**Comment by alandtse** [comment] 2019-04-05 02:17
You need to leave the file names intact.  Also please properly escape statements in markdown using pairs of backticks `. 

Your HA config is wrong. No `>`.  
Proper configuration.yaml below:
`#` are comments and can be ignored but explain the spacing before each section.
```yaml
#no spaces
alexa_media:
#two spaces
  accounts:
#four spaces
    - email: email@email.com
#six spaces
      password: password
      url: amazon.com
```

Please confirm your directory structure matches [here](https://github.com/keatontaylor/alexa_media_player/wiki/Installation-and-Configuration#download-python-files).

Also confirm that all of the .py files are only text and not HTML.  If you copy the first 10 lines in from `__init__.py` I can tell.

A working check config looks like this:
```bash
homeassistant@raspberrypi:~/.homeassistant $ /srv/homeassistant/homeassistant_venv/bin/hass --script check_config
Testing configuration at /home/homeassistant/.homeassistant
```
Assuming check_config works please enable the [HA logger](https://github.com/keatontaylor/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component) so we can see the results from `homeassistant.loader`, `custom_components.alexa_media` and `alexa_py`.  **Please scrub the logs before you post**.

**Comment by sparkyx64** [comment] 2019-04-05 03:19
for the config, the `>` were because of the quote on here, they are not part of the config, indent is proper according to your spacing amount, apologies on the mixup there.

I will post the 10 lines of init.py below.

code here

>#
>#
>#
>#
>#
>#
>!DOCTYPE html
>html lang="en"
>  head
>    meta charset="utf-8"

Again the `>` and removing the `<->` was the only way it would show on here, im not used to github formatting so forgive me...

check_config results below:

> hades@hades:~$ sudo -u homeassistant -H -s
> homeassistant@hades:/home/hades$ cd /srv/homeassistant
> homeassistant@hades:/srv/homeassistant$ source bin/activate
> (homeassistant) homeassistant@hades:/srv/homeassistant$ hass --script check_config
> INFO:homeassistant.util.package:Attempting install of colorlog==4.0.2
> Testing configuration at /home/homeassistant/.homeassistant
> ERROR:homeassistant.scripts.check_config:BURB
> Traceback (most recent call last):
>   File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/scripts/check_config.py", line 204, in check
>     res['components'] = check_ha_config_file(hass)
>   File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/scripts/check_config.py", line 332, in check_ha_config_file
>     component = loader.get_component(hass, domain)
>   File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/loader.py", line 148, in get_component
>     comp = _load_file(hass, comp_or_platform, LOOKUP_PATHS)
>   File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/loader.py", line 183, in _load_file
>     module = importlib.import_module(path)
>   File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 674, in exec_module
>   File "<frozen importlib._bootstrap_external>", line 781, in get_code
>   File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "/home/homeassistant/.homeassistant/custom_components/alexa_media/__init__.py", line 7
>     <!DOCTYPE html>
>     ^
> SyntaxError: invalid syntax
> Fatal error while loading config: invalid syntax (__init__.py, line 7)
> Failed config
>   General Errors: 
>     - invalid syntax (__init__.py, line 7)
> 
> Successful config (partial)
> (homeassistant) homeassistant@hades:/srv/homeassistant$ 

bear with me to get the HA logger up and posted

**Comment by alandtse** [comment] 2019-04-05 03:36
You copied the files wrong from GitHub. You need to use raw mode when downloading any python files.
https://raw.githubusercontent.com/keatontaylor/alexa_media_player/master/alexa_media/__init__.py

GitHub has a `Raw` button you need to select on right side of every page.
![image](https://user-images.githubusercontent.com/7086117/55602162-2058cc00-5719-11e9-9f91-12491e37a586.png)

**Comment by alandtse** [comment] 2019-04-06 02:11
As this is likely the cause, I will close the issue. Feel free to reopen if it's not.

**Closed** 2019-04-06 02:11 UTC
