### ISSUE TITLE
Alexa Guard no longer works after renaming the entity

### ISSUE THREAD

**Issue by FuzzyMistborn** [keatontaylor/alexa_media_player#230] opened 2019-06-25 13:37 UTC
**Describe the bug**
I updated to the latest version and Alexa Guard showed up.  I tested it and it worked fine.  I used the HASS rename function to rename the device (wanted to remove the letters/numbers at the end) and now it doesn't work/show up.  I see the following error in HASS:

```
An error occured accessing AlexaAPI: An exception of type JSONDecodeError occurred. Arguments:
('Expecting value: line 1 column 1 (char 0)',)
```

And a separate error:

```
Error while setting up platform alexa_media
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 126, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/alexa_media/alarm_control_panel.py", line 34, in setup_platform
    hass)  \
  File "/home/homeassistant/.homeassistant/custom_components/alexa_media/alarm_control_panel.py", line 70, in __init__
    guard_dict = (data['locationDetails']
TypeError: 'NoneType' object is not subscriptable
```

**To Reproduce**
Not sure if this is what caused it but try renaming Alexa Guard panel in HASS.

**Expected behavior**
Alexa Guard alarm panel showing up/functioning

**System details**
 - Home-assistant (version): 0.94.3
 - Hassio (Yes/No): No (hassbian)
 - alexa_media  (version from `const.py` or HA startup): 1.3
 - alexapy (version from `pip show alexapy` or HA startup): 0.7

**Comment by alandtse** [comment] 2019-06-25 15:50
Does a restart of HA fix it? The json error happens when the login doesn't connect.

**Comment by FuzzyMistborn** [comment] 2019-06-25 15:51
Nope, restarted and that's the error that popped up on restart.  Think there was a similar error before restart.  Should I delete the pickle file?

**Comment by alandtse** [comment] 2019-06-25 15:53
Odd.  Do the other parts of the component still work? You can try renaming the pickle to see if logging in again with a new cookie fixes it.

**Comment by FuzzyMistborn** [comment] 2019-06-25 16:00
Yep seems to be working otherwise.  I'll try renaming the cookie.

**Comment by FuzzyMistborn** [comment] 2019-06-25 16:06
Nope, same error.  Maybe I need to delete the reference in the .config folder?

**Comment by alandtse** [comment] 2019-06-25 17:00
I don't think that'll do anything. I'l see if I can reproduce it probably this weekend.  You didn't disable Guard inside the Alexa app right?

**Comment by FuzzyMistborn** [comment] 2019-06-25 17:04
Nope, still enabled.

**Comment by FuzzyMistborn** [comment] 2019-06-25 23:19
Update: I cleared the alarm panel from core.entity_registry, restarted, and the alarm showed up again with no error.  So there's something with the renaming that triggered this somehow.

**Comment by alandtse** [comment] 2019-06-26 02:01
Ok thanks for the info. I'll explore that angle although it shouldn't since we don't use the ha entity name for anything.

**Comment by alandtse** [comment] 2019-06-30 07:33
I took a closer look at the code and I don't see why the renaming would do anything. I also tested renaming on my end (both entity_id and name) and didn't see the issues you reported. I am using a newer version that handles the log errors you reported so that may have resolved it.  I'll close this when I make that live.  If you run into it again please let me know.

**Closed** 2019-06-30 07:59 UTC
Labels: bug
