### ISSUE TITLE
Add alexapy module

### ISSUE THREAD

**Issue by trhr** [keatontaylor/alexa_media_player#194] opened 2019-05-22 23:52 UTC
Any reason why this repo doesn't include alexapy? I had to clone it from gitlab to get to the captcha.

**Comment by rccoleman** [comment] 2019-05-23 00:11
It's a requirement in the manifest, so it should be installed automatically the first time HA starts up with this custom component.  I think you'll have to restart again for it to actually use it, though.

**Comment by trhr** [comment] 2019-05-23 00:59
...even in a minimalist docker container that I don't even think has pip?

**Comment by rccoleman** [comment] 2019-05-23 01:04
I can't speak to your installation, but as far as I know, that's how all custom components handle dependencies.  You may be able to do it yourself depending on your installation, but part of the loader's and manifest's job is to install any dependencies from PyPI based on what the author puts in manifest.json (used to be the REQUIREMENTS tag in __init__.py).

**Comment by alandtse** [comment] 2019-05-23 04:31
The split was required by HA by design. As @rccoleman mentioned, manifest.json and HA itself is responsible for loading the declared dependencies. To the extent HA doesn't probably handle custom_components in docker (and you're not the first to have to do extra restarts or manual installs), I think that's a HA bug. I'll close this out for now.

**Closed by alandtse** 2019-05-23 04:31 UTC
Labels: wontfix
