### ISSUE TITLE
websocket error from callback

### ISSUE THREAD

**Issue by mauog** [keatontaylor/alexa_media_player#205] opened 2019-06-08 09:30 UTC
From time to time I got this error in the log:

```
2019-06-08 11:19:10 ERROR (Thread-3) [websocket] error from callback <bound method WebsocketEchoClient.on_open of <WebsocketEchoClient(Thread-3, started daemon 1864981432)>>: [Errno 32] Broken pipe
2019-06-08 11:19:11 ERROR (Thread-3) [alexapy.alexawebsocket] WebSocket Error [SSL: BAD_LENGTH] bad length (_ssl.c:2341)
```

I had to restart HA (often twice) to get rid of it.
I'm using HA 0.93.2 and alexa_media 1.2.5

**Comment by alandtse** [comment] 2019-06-09 00:34
Thanks. Looks like a dupe of #181

**Closed by alandtse** 2019-06-09 00:34 UTC
Labels: duplicate
