### ISSUE TITLE
Component fail to load, login issues occurred

### ISSUE THREAD

**Issue by ohadbenita** [keatontaylor/alexa_media_player#204] opened 2019-06-05 19:31 UTC
Everything worked fabulously until today, when I got this call stack:

`
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/core.py", line 1141, in async_call
    self._execute_service(handler, service_call))
  File "/usr/src/app/homeassistant/core.py", line 1163, in _execute_service
    await handler.func(service_call)
  File "/usr/src/app/homeassistant/helpers/entity_component.py", line 194, in handle_service
    required_features
  File "/usr/src/app/homeassistant/helpers/service.py", line 316, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/app/homeassistant/helpers/service.py", line 337, in _handle_service_platform_call
    await getattr(entity, func)(**data)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/app/homeassistant/components/yeelight/light.py", line 554, in turn_off
    self.device.turn_off(duration=duration, light_type=self.light_type)
  File "/usr/src/app/homeassistant/components/yeelight/__init__.py", line 254, in turn_off
    self.bulb.turn_off(duration=duration, light_type=light_type)
  File "<decorator-gen-8>", line 2, in turn_off
  File "/usr/local/lib/python3.7/site-packages/yeelight/main.py", line 114, in _command
    result = self.send_command(method, params).get("result", [])
  File "/usr/local/lib/python3.7/site-packages/yeelight/main.py", line 397, in send_command
    self.__socket.close()
AttributeError: 'NoneType' object has no attribute 'close'
`

I've tried updating the component's files with no luck
Also updated HA to 0.93.2 which yielded the same results

**Comment by andrewlphilpott** [comment] 2019-06-05 21:00
I'm having issues with login as well and just enabled debugging. It looks like (at least for me) the page that it's trying to load for log in is not available. Maybe that's the cause of your problem as well.

**Comment by alandtse** [comment] 2019-06-06 06:21
The log above doesn't say anything about the component. I'll need to see a log with debugging on to figure it out. I just checked the US login page we use and it looks like it's still live so unless it's a different region with the problem, I'm not sure that's the issue.

**Comment by andrewlphilpott** [comment] 2019-06-06 11:39
Looks like the log in page is loading correctly for me now.

**Comment by alandtse** [comment] 2019-06-17 00:00
Gonna close this since the logs don't show anything I can debug. Please reopen if you're still having an issue.

**Closed by alandtse** 2019-06-17 00:00 UTC
